--create user data
INSERT INTO USERS
VALUES (1, true, '$2a$10$lRxHIjkZpcNszfquVB7dBuvLy65dXKW6ZakDjjgicVbOlUAO0ssNa', 'DEV', 'sai');
INSERT INTO USERS
VALUES (2, true, '$2a$10$lRxHIjkZpcNszfquVB7dBuvLy65dXKW6ZakDjjgicVbOlUAO0ssNa', 'DEV,ADMIN', 'ram');
INSERT INTO USERS
VALUES (3, true, '$2a$10$lRxHIjkZpcNszfquVB7dBuvLy65dXKW6ZakDjjgicVbOlUAO0ssNa', 'ADMIN', 'kumar');
-- create LoyaltyPoints table
--INSERT INTO ROLE VALUES (1,50.00,1);
--INSERT INTO ROLE VALUES (2,100.00,2);
-- iNSERT INTO points
INSERT INTO REWARD_POINTS  VALUES(1,1,50.00);
INSERT INTO REWARD_POINTS  VALUES(2,2,100.00);

insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (1, 'cseathwright0@theatlantic.com', 'Caspar', 'Seathwright', '1113634655');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (2, 'jqusklay1@surveymonkey.com', 'Johnette', 'Qusklay', '3043032304');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (3, 'rscambler2@twitpic.com', 'Reinhold', 'Scambler', '7686328762');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (4, 'mlabell3@tinypic.com', 'Montgomery', 'Labell', '6245995542');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (5, 'gavraam4@fema.gov', 'Godfry', 'Avraam', '8695565970');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (6, 'aocaherny5@samsung.com', 'Arv', 'O''Caherny', '5622381498');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (7, 'vallen6@pen.io', 'Virgie', 'Allen', '2832991480');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (8, 'bvalentetti7@blog.com', 'Bax', 'Valentetti', '7383526809');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (9, 'ffishley8@mail.ru', 'Faustina', 'Fishley', '4043200229');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (10, 'jahrendsen9@china.com.cn', 'Johann', 'Ahrendsen', '7395272162');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (11, 'ehacarda@delicious.com', 'Eugenie', 'Hacard', '5092998536');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (12, 'jchurmb@flavors.me', 'Jenilee', 'Churm', '6199528145');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (13, 'vheustacec@infoseek.co.jp', 'Val', 'Heustace', '7551819116');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (14, 'lslowleyd@e-recht24.de', 'Lilyan', 'Slowley', '4439951976');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (15, 'aorrockse@noaa.gov', 'Antoni', 'Orrocks', '5885960678');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (16, 'vjeffelsf@youtube.com', 'Vilhelmina', 'Jeffels', '9334044454');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (17, 'urambadtg@bbb.org', 'Ulises', 'Rambadt', '9086439337');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (18, 'kbirrelh@eepurl.com', 'Kalvin', 'Birrel', '8148367389');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (19, 'breinhardti@indiatimes.com', 'Brian', 'Reinhardt', '2985833657');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (20, 'amangeotj@ow.ly', 'Amie', 'Mangeot', '4483345926');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (21, 'dstollsteimerk@woothemes.com', 'Dulci', 'Stollsteimer', '9027734753');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (22, 'vholseyl@usgs.gov', 'Vinny', 'Holsey', '5124926585');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (23, 'atrunkfieldm@instagram.com', 'Aggi', 'Trunkfield', '4873075373');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (24, 'cpavicn@businessweek.com', 'Carissa', 'Pavic', '9076108540');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (25, 'asalltero@behance.net', 'Antoinette', 'Sallter', '7945148318');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (26, 'msedgemorep@ca.gov', 'Melisse', 'Sedgemore', '3658130706');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (27, 'cstaceq@slate.com', 'Christa', 'Stace', '1869089786');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (28, 'dosharkeyr@paginegialle.it', 'Devin', 'O''Sharkey', '5629669270');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (29, 'mleggss@usda.gov', 'Martguerita', 'Leggs', '1857228758');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (30, 'mlangfittt@newsvine.com', 'Merrick', 'Langfitt', '7401761487');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (31, 'pmeinu@usgs.gov', 'Patricia', 'Mein', '5646623149');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (32, 'dtweedliev@bing.com', 'Dar', 'Tweedlie', '6155307926');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (33, 'ababidgew@unblog.fr', 'Avis', 'Babidge', '4097485919');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (34, 'jdymidowskix@google.cn', 'Janetta', 'Dymidowski', '2339734360');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (35, 'bwainery@quantcast.com', 'Bancroft', 'Wainer', '3937128976');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (36, 'rlittellz@acquirethisname.com', 'Redford', 'Littell', '2466397598');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (37, 'abreydin10@wunderground.com', 'Aldous', 'Breydin', '6117341091');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (38, 'fpritchett11@forbes.com', 'Felipa', 'Pritchett', '7192286839');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (39, 'cgajewski12@bbb.org', 'Colline', 'Gajewski', '4057486160');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (40, 'adelias13@oracle.com', 'Adelaide', 'D''Elias', '1721366933');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (41, 'glangtree14@wunderground.com', 'Ginger', 'Langtree', '9538450376');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (42, 'sgilders15@weather.com', 'Scotty', 'Gilders', '6352208896');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (43, 'rsnoxall16@elegantthemes.com', 'Rene', 'Snoxall', '3101525062');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (44, 'pegar17@irs.gov', 'Pernell', 'Egar', '3294839450');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (45, 'amocker18@umn.edu', 'Amie', 'Mocker', '2522499986');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (46, 'tconcannon19@columbia.edu', 'Tallia', 'Concannon', '6449274233');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (47, 'mpercifull1a@cnbc.com', 'Marion', 'Percifull', '9056410357');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (48, 'dimmer1b@github.com', 'Dylan', 'Immer', '2076461665');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (49, 'ccudiff1c@cnet.com', 'Cristabel', 'Cudiff', '8536082105');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (50, 'mrigglesford1d@slideshare.net', 'Maudie', 'Rigglesford', '2918568352');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (51, 'creiglar1e@odnoklassniki.ru', 'Ced', 'Reiglar', '8773664063');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (52, 'kkermeen1f@behance.net', 'Keely', 'Kermeen', '4696782453');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (53, 'bhalleybone1g@pagesperso-orange.fr', 'Berta', 'Halleybone', '3094449329');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (54, 'ecurry1h@opensource.org', 'Emmerich', 'Curry', '1658675076');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (55, 'rsherrard1i@europa.eu', 'Raynard', 'Sherrard', '8737788142');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (56, 'ffaireclough1j@tripod.com', 'Filippo', 'Faireclough', '2564243720');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (57, 'kondrousek1k@usatoday.com', 'Kristo', 'Ondrousek', '1121410973');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (58, 'bmaurice1l@sogou.com', 'Barry', 'Maurice', '6601880175');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (59, 'hcuruclis1m@about.com', 'Hyacinthia', 'Curuclis', '7435873285');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (60, 'lmacknight1n@github.io', 'Lyndsey', 'MacKnight', '9589606823');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (61, 'spabel1o@dyndns.org', 'Sholom', 'Pabel', '6436262228');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (62, 'ghellis1p@netvibes.com', 'Guy', 'Hellis', '1993800174');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (63, 'atruelove1q@vk.com', 'Andree', 'Truelove', '9571778776');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (64, 'gskedgell1r@creativecommons.org', 'Garv', 'Skedgell', '9432072253');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (65, 'nmoreno1s@reuters.com', 'Nadiya', 'Moreno', '7441901684');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (66, 'mtschirschky1t@example.com', 'Melessa', 'Tschirschky', '2933158612');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (67, 'rhesbrook1u@google.nl', 'Red', 'Hesbrook', '3775870602');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (68, 'ngregorin1v@baidu.com', 'Nissy', 'Gregorin', '9964224337');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (69, 'bgavahan1w@washington.edu', 'Bevin', 'Gavahan', '9301074915');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (70, 'bjinkins1x@dion.ne.jp', 'Bobby', 'Jinkins', '6289754502');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (71, 'lwheowall1y@ask.com', 'Lars', 'Wheowall', '4181778274');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (72, 'llebell1z@flavors.me', 'Lynett', 'Lebell', '4651048297');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (73, 'eramos20@google.ru', 'Elsbeth', 'Ramos', '1791348762');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (74, 'khof21@domainmarket.com', 'Kelsi', 'Hof', '8228045584');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (75, 'efedynski22@disqus.com', 'Engelbert', 'Fedynski', '2515399767');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (76, 'ycunnah23@xrea.com', 'Yvette', 'Cunnah', '3737482313');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (77, 'sledward24@noaa.gov', 'Shaughn', 'Ledward', '1431216528');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (78, 'cshearsby25@si.edu', 'Cassandra', 'Shearsby', '9799325754');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (79, 'mcrichton26@paypal.com', 'Marabel', 'Crichton', '1129427790');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (80, 'sgodley27@domainmarket.com', 'Sisile', 'Godley', '6579652453');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (81, 'ckermott28@digg.com', 'Christine', 'Kermott', '9055256847');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (82, 'zatwell29@google.nl', 'Zitella', 'Atwell', '9328471977');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (83, 'afraczkiewicz2a@state.gov', 'Addy', 'Fraczkiewicz', '3141450452');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (84, 'wbasindale2b@weebly.com', 'Willdon', 'Basindale', '4302969006');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (85, 'mhyslop2c@networkadvertising.org', 'Mala', 'Hyslop', '7289083636');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (86, 'lferro2d@bloglines.com', 'Lindsey', 'Ferro', '9883616936');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (87, 'baldersea2e@cnet.com', 'Barb', 'Aldersea', '4858086969');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (88, 'pcarrivick2f@addthis.com', 'Pen', 'Carrivick', '3788762802');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (89, 'galabaster2g@time.com', 'Gerladina', 'Alabaster', '9603289948');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (90, 'ozuanazzi2h@indiegogo.com', 'Ozzy', 'Zuanazzi', '4744209440');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (91, 'rsharland2i@digg.com', 'Renard', 'Sharland', '7668163750');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (92, 'libell2j@uiuc.edu', 'Llywellyn', 'Ibell', '5792502197');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (93, 'dkillock2k@canalblog.com', 'Drusie', 'Killock', '2626768316');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (94, 'nmilkin2l@shareasale.com', 'Neill', 'Milkin', '1661327058');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (95, 'tkildale2m@deliciousdays.com', 'Tremaine', 'Kildale', '3245591425');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (96, 'jbrackenbury2n@cornell.edu', 'Joseph', 'Brackenbury', '2218698949');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (97, 'lgoodbarr2o@wisc.edu', 'Legra', 'Goodbarr', '5621809655');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (98, 'gmaisey2p@admin.ch', 'Gussy', 'Maisey', '7227716184');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (99, 'tslot2q@goo.ne.jp', 'Tab', 'Slot', '9899851998');
insert into CUSTOMER (customer_id, email, first_name, last_name, mobile) values (100, 'aanderl2r@fema.gov', 'Arielle', 'Anderl', '4112397252');


insert into TRANSACTION (TRANSACTION_ID, AMOUNT, LOCATION, PARTICULARS, POINTS, REFUND, STATUS , TIME, CUSTOMER_ID) values (9, '884.14', 'Črenšovci', 'Milk - 2%', 7, true, 3, '2022-05-05', 59);
insert into TRANSACTION (TRANSACTION_ID, AMOUNT, LOCATION, PARTICULARS, POINTS, REFUND, STATUS , TIME, CUSTOMER_ID) values (10, '657.82', 'Nazca', 'Molasses - Fancy', 8, false, 3, '2022-02-02', 17);
insert into TRANSACTION (TRANSACTION_ID, AMOUNT, LOCATION, PARTICULARS, POINTS, REFUND, STATUS , TIME, CUSTOMER_ID) values (981, '171.93', 'Nesterovskaya', 'Beer - Tetleys', 8, true, 3, '2022-11-01', 72);
insert into TRANSACTION (TRANSACTION_ID, AMOUNT, LOCATION, PARTICULARS, POINTS, REFUND, STATUS , TIME, CUSTOMER_ID) values (968, '377.24', 'Granja', 'Rosemary - Primerba, Paste', 7, false, 3, '2022-04-21', 4);
